name: Deployment
on:
  push:
    branches:
      - master
      - staging
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Create Vite build, sync to S3, & invalidate Cloudfront
        run: |
          npm install
          npx vite build --mode ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
          aws s3 sync --delete ./dist s3://heythisischris-web${{ github.ref == 'refs/heads/master' && '' || '-staging' }}
          aws cloudfront create-invalidation --distribution-id ${{ github.ref == 'refs/heads/master' && 'EE4MB27CPKA5P' || 'E1F7ZZT6JX48L5' }} --paths \"/*\" > /dev/null"
